const newArray = [
    {
        id: 1,
        img: "https://nov-gearnix.myshopify.com/cdn/shop/articles/IMG_9-min_855x450_crop_center.jpg?v=1724730389",
        title: "Level Up Your Setup Essential Gear for Competitive Gaming",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus venenatis ex, et ultricies nunc molestie ut. Nullam accumsan id nisi vel convallis. Sed dui risus, ullamcorper vitae aliquet vitae, feugiat in neque. Praesent egestas ligula velit, sed malesuada erat interdum vitae. Aliquam pretium nisi sed turpis posuere pharetra. Suspendisse faucibus, sem at egestas viverra, erat velit luctus mi, placerat vulputate dui eros a diam. Aliquam facilisis ut massa et gravida. Morbi sed ipsum magna. Nulla elementum finibus dolor pretium condimentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc gravida diam ac convallis rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent at eros diam. Vivamus a pretium orci. Ut sollicitudin posuere libero vitae rhoncus. Maecenas ultrices, purus ac fermentum tincidunt, nunc leo sagittis erat, vel volutpat dolor justo id lacus. Quisque feugiat imperdiet laoreet. Nunc eget dui ut metus rhoncus volutpat. Morbi luctus tristique lobortis. In mi erat, condimentum eu elementum sit amet, facilisis pellentesque velit. Aenean at est a mauris fermentum luctus. Aliquam erat volutpat. Aliquam eget vehicula purus. Integer pretium egestas metus sed rutrum. Nullam quis felis ultricies, vehicula magna ac, sodales elit. Suspendisse mi massa, porttitor at pharetra sit amet, faucibus eget diam. Ut nec erat tellus. Vestibulum lobortis mi a dui maximus, et eleifend augue volutpat. In tincidunt nisl a interdum facilisis. Vivamus nec tempus turpis. Nullam volutpat massa sed neque cursus porta. Integer non metus consequat, dignissim justo iaculis, venenatis sem. Phasellus imperdiet facilisis felis a fermentum. Suspendisse sit amet ex eu dui pretium laoreet sit amet sit amet nulla. Morbi ut leo ac nibh cursus cursus. In in elit urna. Quisque commodo vestibulum purus sed volutpat. Praesent quis tellus ac nulla rutrum sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean eget volutpat justo. Quisque nec ex tortor. Integer a felis aliquet, mollis orci id, porttitor sapien. Nulla arcu ipsum, sollicitudin et faucibus eu, efficitur in metus. Nunc pharetra arcu arcu, et porttitor massa varius eget. Morbi nisi turpis, gravida a ligula id, volutpat placerat nulla. Sed ut mi at odio commodo rhoncus et id arcu. Ut ultrices lacinia neque ac feugiat. Suspendisse elementum non nibh in tempor. Vivamus convallis augue a malesuada ullamcorper.",
    },
    {
        id: 2,
        img: "https://nov-gearnix.myshopify.com/cdn/shop/articles/IMG_8-min_855x450_crop_center.jpg?v=1724730372",
        title: "Ultimate Guide to Choosing the Best Gaming Gear for Every Gamer",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus venenatis ex, et ultricies nunc molestie ut. Nullam accumsan id nisi vel convallis. Sed dui risus, ullamcorper vitae aliquet vitae, feugiat in neque. Praesent egestas ligula velit, sed malesuada erat interdum vitae. Aliquam pretium nisi sed turpis posuere pharetra. Suspendisse faucibus, sem at egestas viverra, erat velit luctus mi, placerat vulputate dui eros a diam. Aliquam facilisis ut massa et gravida. Morbi sed ipsum magna. Nulla elementum finibus dolor pretium condimentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc gravida diam ac convallis rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent at eros diam. Vivamus a pretium orci. Ut sollicitudin posuere libero vitae rhoncus. Maecenas ultrices, purus ac fermentum tincidunt, nunc leo sagittis erat, vel volutpat dolor justo id lacus. Quisque feugiat imperdiet laoreet. Nunc eget dui ut metus rhoncus volutpat. Morbi luctus tristique lobortis. In mi erat, condimentum eu elementum sit amet, facilisis pellentesque velit. Aenean at est a mauris fermentum luctus. Aliquam erat volutpat. Aliquam eget vehicula purus. Integer pretium egestas metus sed rutrum. Nullam quis felis ultricies, vehicula magna ac, sodales elit. Suspendisse mi massa, porttitor at pharetra sit amet, faucibus eget diam. Ut nec erat tellus. Vestibulum lobortis mi a dui maximus, et eleifend augue volutpat. In tincidunt nisl a interdum facilisis. Vivamus nec tempus turpis. Nullam volutpat massa sed neque cursus porta. Integer non metus consequat, dignissim justo iaculis, venenatis sem. Phasellus imperdiet facilisis felis a fermentum. Suspendisse sit amet ex eu dui pretium laoreet sit amet sit amet nulla. Morbi ut leo ac nibh cursus cursus. In in elit urna. Quisque commodo vestibulum purus sed volutpat. Praesent quis tellus ac nulla rutrum sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean eget volutpat justo. Quisque nec ex tortor. Integer a felis aliquet, mollis orci id, porttitor sapien. Nulla arcu ipsum, sollicitudin et faucibus eu, efficitur in metus. Nunc pharetra arcu arcu, et porttitor massa varius eget. Morbi nisi turpis, gravida a ligula id, volutpat placerat nulla. Sed ut mi at odio commodo rhoncus et id arcu. Ut ultrices lacinia neque ac feugiat. Suspendisse elementum non nibh in tempor. Vivamus convallis augue a malesuada ullamcorper.",
    },
    {
        id: 3,
        img: "https://nov-gearnix.myshopify.com/cdn/shop/articles/IMG_7-min_855x450_crop_center.jpg?v=1724730407",
        title: "The Impact of High-Quality Headsets on Your Gaming Experience",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus venenatis ex, et ultricies nunc molestie ut. Nullam accumsan id nisi vel convallis. Sed dui risus, ullamcorper vitae aliquet vitae, feugiat in neque. Praesent egestas ligula velit, sed malesuada erat interdum vitae. Aliquam pretium nisi sed turpis posuere pharetra. Suspendisse faucibus, sem at egestas viverra, erat velit luctus mi, placerat vulputate dui eros a diam. Aliquam facilisis ut massa et gravida. Morbi sed ipsum magna. Nulla elementum finibus dolor pretium condimentum.Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc gravida diam ac convallis rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent at eros diam. Vivamus a pretium orci. Ut sollicitudin posuere libero vitae rhoncus. Maecenas ultrices, purus ac fermentum tincidunt, nunc leo sagittis erat, vel volutpat dolor justo id lacus. Quisque feugiat imperdiet laoreet. Nunc eget dui ut metus rhoncus volutpat. Morbi luctus tristique lobortis. In mi erat, condimentum eu elementum sit amet, facilisis pellentesque velit. Aenean at est a mauris fermentum luctus. Aliquam erat volutpat. Aliquam eget vehicula purus. Integer pretium egestas metus sed rutrum.Nullam quis felis ultricies, vehicula magna ac, sodales elit. Suspendisse mi massa, porttitor at pharetra sit amet, faucibus eget diam. Ut nec erat tellus. Vestibulum lobortis mi a dui maximus, et eleifend augue volutpat. In tincidunt nisl a interdum facilisis. Vivamus nec tempus turpis. Nullam volutpat massa sed neque cursus porta. Integer non metus consequat, dignissim justo iaculis, venenatis sem. Phasellus imperdiet facilisis felis a fermentum.Suspendisse sit amet ex eu dui pretium laoreet sit amet sit amet nulla. Morbi ut leo ac nibh cursus cursus. In in elit urna. Quisque commodo vestibulum purus sed volutpat. Praesent quis tellus ac nulla rutrum sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean eget volutpat justo. Quisque nec ex tortor. Integer a felis aliquet, mollis orci id, porttitor sapien. Nulla arcu ipsum, sollicitudin et faucibus eu, efficitur in metus. Nunc pharetra arcu arcu, et porttitor massa varius eget. Morbi nisi turpis, gravida a ligula id, volutpat placerat nulla. Sed ut mi at odio commodo rhoncus et id arcu. Ut ultrices lacinia neque ac feugiat. Suspendisse elementum non nibh in tempor. Vivamus convallis augue a malesuada ullamcorper.",
    },
    {
        id: 4,
        img: "https://nov-gearnix.myshopify.com/cdn/shop/articles/IMG_6-min_855x450_crop_center.jpg?v=1724730431",
        title: "Top 10 Must-Have Gaming Accessories for Every Gamer",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus venenatis ex, et ultricies nunc molestie ut. Nullam accumsan id nisi vel convallis. Sed dui risus, ullamcorper vitae aliquet vitae, feugiat in neque. Praesent egestas ligula velit, sed malesuada erat interdum vitae. Aliquam pretium nisi sed turpis posuere pharetra. Suspendisse faucibus, sem at egestas viverra, erat velit luctus mi, placerat vulputate dui eros a diam. Aliquam facilisis ut massa et gravida. Morbi sed ipsum magna. Nulla elementum finibus dolor pretium condimentum.Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc gravida diam ac convallis rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent at eros diam. Vivamus a pretium orci. Ut sollicitudin posuere libero vitae rhoncus. Maecenas ultrices, purus ac fermentum tincidunt, nunc leo sagittis erat, vel volutpat dolor justo id lacus. Quisque feugiat imperdiet laoreet. Nunc eget dui ut metus rhoncus volutpat. Morbi luctus tristique lobortis. In mi erat, condimentum eu elementum sit amet, facilisis pellentesque velit. Aenean at est a mauris fermentum luctus. Aliquam erat volutpat. Aliquam eget vehicula purus. Integer pretium egestas metus sed rutrum.Nullam quis felis ultricies, vehicula magna ac, sodales elit. Suspendisse mi massa, porttitor at pharetra sit amet, faucibus eget diam. Ut nec erat tellus. Vestibulum lobortis mi a dui maximus, et eleifend augue volutpat. In tincidunt nisl a interdum facilisis. Vivamus nec tempus turpis. Nullam volutpat massa sed neque cursus porta. Integer non metus consequat, dignissim justo iaculis, venenatis sem. Phasellus imperdiet facilisis felis a fermentum.Suspendisse sit amet ex eu dui pretium laoreet sit amet sit amet nulla. Morbi ut leo ac nibh cursus cursus. In in elit urna. Quisque commodo vestibulum purus sed volutpat. Praesent quis tellus ac nulla rutrum sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean eget volutpat justo. Quisque nec ex tortor. Integer a felis aliquet, mollis orci id, porttitor sapien. Nulla arcu ipsum, sollicitudin et faucibus eu, efficitur in metus. Nunc pharetra arcu arcu, et porttitor massa varius eget. Morbi nisi turpis, gravida a ligula id, volutpat placerat nulla. Sed ut mi at odio commodo rhoncus et id arcu. Ut ultrices lacinia neque ac feugiat. Suspendisse elementum non nibh in tempor. Vivamus convallis augue a malesuada ullamcorper.",
    },
    {
        id: 5,
        img: "https://nov-gearnix.myshopify.com/cdn/shop/articles/IMG_5-min_855x450_crop_center.jpg?v=1724730448",
        title: "How to Choose the Perfect Gaming Mouse A Complete Guide",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus venenatis ex, et ultricies nunc molestie ut. Nullam accumsan id nisi vel convallis. Sed dui risus, ullamcorper vitae aliquet vitae, feugiat in neque. Praesent egestas ligula velit, sed malesuada erat interdum vitae. Aliquam pretium nisi sed turpis posuere pharetra. Suspendisse faucibus, sem at egestas viverra, erat velit luctus mi, placerat vulputate dui eros a diam. Aliquam facilisis ut massa et gravida. Morbi sed ipsum magna. Nulla elementum finibus dolor pretium condimentum.Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc gravida diam ac convallis rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent at eros diam. Vivamus a pretium orci. Ut sollicitudin posuere libero vitae rhoncus. Maecenas ultrices, purus ac fermentum tincidunt, nunc leo sagittis erat, vel volutpat dolor justo id lacus. Quisque feugiat imperdiet laoreet. Nunc eget dui ut metus rhoncus volutpat. Morbi luctus tristique lobortis. In mi erat, condimentum eu elementum sit amet, facilisis pellentesque velit. Aenean at est a mauris fermentum luctus. Aliquam erat volutpat. Aliquam eget vehicula purus. Integer pretium egestas metus sed rutrum.Nullam quis felis ultricies, vehicula magna ac, sodales elit. Suspendisse mi massa, porttitor at pharetra sit amet, faucibus eget diam. Ut nec erat tellus. Vestibulum lobortis mi a dui maximus, et eleifend augue volutpat. In tincidunt nisl a interdum facilisis. Vivamus nec tempus turpis. Nullam volutpat massa sed neque cursus porta. Integer non metus consequat, dignissim justo iaculis, venenatis sem. Phasellus imperdiet facilisis felis a fermentum.Suspendisse sit amet ex eu dui pretium laoreet sit amet sit amet nulla. Morbi ut leo ac nibh cursus cursus. In in elit urna. Quisque commodo vestibulum purus sed volutpat. Praesent quis tellus ac nulla rutrum sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean eget volutpat justo. Quisque nec ex tortor. Integer a felis aliquet, mollis orci id, porttitor sapien. Nulla arcu ipsum, sollicitudin et faucibus eu, efficitur in metus. Nunc pharetra arcu arcu, et porttitor massa varius eget. Morbi nisi turpis, gravida a ligula id, volutpat placerat nulla. Sed ut mi at odio commodo rhoncus et id arcu. Ut ultrices lacinia neque ac feugiat. Suspendisse elementum non nibh in tempor. Vivamus convallis augue a malesuada ullamcorper.",
    },
]
export default newArray
